// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM8QS21dkNMeOiLUgAKscUmkXpy98jnI8',
    appId: '1:172451489286:web:d343984de1a70e7ee98587',
    messagingSenderId: '172451489286',
    projectId: 'kbc-yt-1205f',
    authDomain: 'kbc-yt-1205f.firebaseapp.com',
    storageBucket: 'kbc-yt-1205f.appspot.com',
    measurementId: 'G-PGG4RB9QDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv_ttmClmJb9WCc3bdvCAIzWEVhj935MI',
    appId: '1:172451489286:android:1c28b049a1507032e98587',
    messagingSenderId: '172451489286',
    projectId: 'kbc-yt-1205f',
    storageBucket: 'kbc-yt-1205f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNqbkzP-5KLyjqCAPNir9aUTC-5Qdlpbo',
    appId: '1:172451489286:ios:ac0a400f337997ade98587',
    messagingSenderId: '172451489286',
    projectId: 'kbc-yt-1205f',
    storageBucket: 'kbc-yt-1205f.appspot.com',
    iosClientId: '172451489286-kd98f8ee52abioqf8b7el85ab6i4rohh.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNqbkzP-5KLyjqCAPNir9aUTC-5Qdlpbo',
    appId: '1:172451489286:ios:ac0a400f337997ade98587',
    messagingSenderId: '172451489286',
    projectId: 'kbc-yt-1205f',
    storageBucket: 'kbc-yt-1205f.appspot.com',
    iosClientId: '172451489286-kd98f8ee52abioqf8b7el85ab6i4rohh.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM8QS21dkNMeOiLUgAKscUmkXpy98jnI8',
    appId: '1:172451489286:web:d346dd329fbf2d43e98587',
    messagingSenderId: '172451489286',
    projectId: 'kbc-yt-1205f',
    authDomain: 'kbc-yt-1205f.firebaseapp.com',
    storageBucket: 'kbc-yt-1205f.appspot.com',
    measurementId: 'G-R7E9YHBNEY',
  );
}
